print('----------ch.1------------------')
import numpy as np 
array = np.array([
	[1,2,3],
	[2,3,4]
])
print(array)
print('number of dim:',array.ndim)
print('shape:',array.shape)
print('size:',array.size)
print('\n')

print('----------ch.2------------------')
a = np.array([2,23,4],dtype=np.float)
print('a\'s tpye:',a.dtype)
b = np.ones( (3,4))
print('ones:',b)
c = np.zeros( (3,4))
print('zeros:',c)
d = np.empty( (3,4) )
print('empty:',d)
e = np.arange(10,20,2)
print('arange from 10 to 20, step is 2:',e)
f = np.arange(12).reshape( (3,4) )
print('reshape 3*4:',f)
g = np.linspace(1,10,19)
print('linspace:',g)
print('\n')

print('----------ch.3------------------')
a = np.array([10,20,30,40])
b = np.arange(4)
print('a and b:',a,b)
print('a - b:',a - b)
print('b^2:',b**2)
print('10*np.sin(a):',10*np.sin(a))
print('a<25?:',a < 25)
print('b=2?:',b == 2)
c = np.array([
	[0,1],
	[2,3]
])
d  = np.arange(4).reshape((2,2))
print('c and d:',c,d)
print('c*d:',c*d)
print('dot(c,d):',np.dot(c,d))
print('c.dot(d):',c.dot(d))
e = np.random.random((2,4))
print('random:',e)

print('sum:',np.sum(e))
print('sum(axis=1):',np.sum(e,axis=1))
print('sum(axis=0):',np.sum(e,axis=0))
print('min',np.min(e))
print('max',np.max(e))
print('\n')

print('----------ch.4------------------')
A = np.arange(0,12).reshape( (3,4) )
print('A:',A)
print('arg_min:',np.argmin(A))
print('arg_max:',np.argmax(A))
print('median_of_A::',np.median(A))
print('mean_of_A::',np.mean(A))
print('mean_of_A::',A.mean())
print('average_of_A::',np.average(A))
print('cumsum_of_A::',np.cumsum(A))
print('diff_of_A::',np.diff(A))
print('nonzero_of_A::',np.nonzero(A))  #输出非零元素的横纵坐标
print('diff_of_A::',np.diff(A))
print('sort:',np.sort(A))
print('transpose_of_A::',np.transpose(A))
print('transpose_of_A::',A.T)
print('clip_of_A::',np.clip(A,5,9))
print('\n')

print('----------ch.5------------------')
A = np.arange(3,15).reshape( (3,4) )
print('A:',A)
print('A[2,2]:',A[2,2])
print('A[2]:',A[2])
print('A[:,2]:',A[:,2])
print('flatten:',A.flatten())
for row in A:
	print('every row:',row)
for column in A.T:
	print('every column',column)
for item in A.flat:
	print('every item',item)
print('\n')

print('----------ch.6------------------')
A = np.array([1,1,1])
B = np.array([2,2,2])
print('vertical stack:',np.vstack((A,B)))
print('horizontal stack:',np.hstack((A,B)))
#print(A.T)
print('newaxis1:',A[np.newaxis,:])
print('newaxis2:',A[:,np.newaxis])
print('mul_stack1:',np.concatenate((A,B,B,A)))
print('\n')

print('----------ch.7------------------')
A = np.arange(12).reshape( (3,4) )
print('A:',A)
print('split:',np.split(A,2,axis=1))
print('split:',np.array_split(A,3,axis=1))
print('split:',np.hsplit(A,2))
print('\n')

print('----------ch.8------------------')
a = np.arange(4)
print('a:',a)
b = a
c = a.copy()
print('b:',b)
print('c:',c)
a[0] = 99
print('new a:',a)
print('new b:',b)
print('new c(deep copy):',c)

